name: Download/upload

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run custom script
        run: |
          curl -O https://raw.githubusercontent.com/koodo-reader/koodo-reader/master/src/upload.sh
          chmod +x ./upload.sh
          ./upload.sh ${{ secrets.R2_ACCOUNT_ID }} ${{ secrets.R2_APPLICATION_KEY }} ${{ secrets.R2_ENDPOINT }} v1.7.0
        shell: bash
